'use client'
import { ChakraProvider, chakra } from '@chakra-ui/react'
import { CacheProvider } from '@chakra-ui/next-js'
import { Flex } from '@chakra-ui/react'
import './globals.css'
import { Inter } from 'next/font/google'

//components
import { Navbar } from './components/Navbar'
import {Footer} from './components/Footer'


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }:any) {
  return ( 
    <html lang="en">
      <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet"></link>
      </head>
    
      <body className={inter.className}>

        <Navbar />
        <CacheProvider>
        <ChakraProvider>

        <main>{children}</main>
        </ChakraProvider>
        </CacheProvider>
        <Footer />
  
        </body>

    </html>
  )
  
}


