"use client";
import { Box, ChakraProvider, chakra } from "@chakra-ui/react";
import { CacheProvider } from "@chakra-ui/next-js";
import { Flex } from "@chakra-ui/react";
import "./globals.css";
import { Inter } from "next/font/google";
import { useState, useEffect, useRef } from 'react';

//components
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { getCookie } from "cookies-next";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: any) {
  const [user, setUser] = useState(null)

  const getUserCookie = async () => {
    const cookie = getCookie('user')
    console.log("Cookie value:", cookie);  // Debug log
  
    if (cookie) {
      const user = JSON.parse(cookie)
      setUser(user)
      console.log("User set:", user);  // Debug log
    }
  }

  useEffect(() => {
    const fetchUserCookie = async () => {
      await getUserCookie();
    };
    
    fetchUserCookie();
  }, [])

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap"
          rel="stylesheet"
        ></link>
      </head>

      <body>
        <CacheProvider>
          <ChakraProvider>
          <Navbar />
            <Box minH={'100dvh'}>{children}</Box>
            <Footer />
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
